defaults:
  - data: devbox_debug_raw_audio_static_batch
  - machine: devbox
  - audiowebdataset: runtime_dataset_audiowebdataset
  - model: codec_model/dac_12hz_dual_16384_4096_causal_16codebook
  # - model: codec_model/dac_25hz_dual_16384_1024_causal
  - trainer: codec_model_trainer
  - _self_
hydra:
  run:
    dir: ${machine.log_dir}/${trainer.exp_name}

# data:
#   dataset:
#     cfg:
#       skip_existing_batches: true
#       skip_batch_list: ${trainer.args.resume_from_ckpt_path}
trainer:
  exp_name: dac_25hz_dual_16384_1024_causal_general_audio_data
  dataloader: ${audiowebdataset.combined_dataloader}
  max_tokens: 2000
  batch_size: 1
  combined_dataloader_batch_size: 12
  args:
    resume: true
    reset_steps: true
    resume_from_ckpt_path: ${machine.init_model_path}/resume_ckpts/epoch-0002_step-0820000_loss-0.000000-dac_12hz_dual_16384_4096_causal_16codebook/
    # resume_from_ckpt_path: ${machine.init_model_path}/resume_ckpts/epoch-0002_step-1480000_loss-0.000000-dac_25hz_dual_16384_1024_causal/
  cfg:
    semantic_vq: true
    lambda_semantic_commitment_loss: 0.25
    lambda_semantic_codebook_loss: 1.0
    lambda_distill_loss: 15.0
    add_semantic_spec_loss: true
    train:
      max_steps: 1000000
      save_checkpoint_stride:
        - 20000
      keep_last: [1]
      disable_mixed_precision: true
