# This is the baseline model. 
#
# SAMPLE_RATE: 24000
# model:
#   _target_: dualcodec.model_codec.DualCodec
#   sample_rate: ${..SAMPLE_RATE}
#   encoder_rates: [6, 5, 2, 8, 4]
#   decoder_rates: [4, 8, 2, 5, 6]
#   encoder_dim: 32
#   decoder_dim: 1536
#   n_codebooks: 7
#   quantizer_dropout: 1.0
#   codebook_size: 4096
#   semantic_codebook_size: 16384
#   is_causal: true
#   semantic_downsample_factor: 4
# discriminator:
#   _target_: dualcodec.model_codec.Discriminator
#   sample_rate: ${..SAMPLE_RATE}


# We have changed the order of the decoder and encoder rates to 
# lower the receptive field of the model. feel free to play around with the rates.

SAMPLE_RATE: 24000
model:
  _target_: dualcodec.model_codec.DualCodec
  sample_rate: ${..SAMPLE_RATE}
  encoder_rates: [4, 5, 6, 8, 2]
  decoder_rates: [4, 8, 2, 5, 6]
  encoder_dim: 32
  decoder_dim: 1536
  n_codebooks: 7
  quantizer_dropout: 1.0
  codebook_size: 4096
  semantic_codebook_size: 16384
  make_convnext_causal: true
  make_dac_causal: true
  add_dac_look_ahead: false
  semantic_downsample_factor: 4
  semantic_repr_dim: 512
discriminator:
  _target_: dualcodec.model_codec.Discriminator
  sample_rate: ${..SAMPLE_RATE}