defaults:
  - data: emilia_hf_raw_audio_static_batch_with_whisper
  - machine: devbox
  - model: dualcodec_12hz_16384_4096_8vq
  - trainer: codec_model_with_whisper
  - _self_
hydra:
  run:
    dir: ${machine.log_dir}/${trainer.exp_name}

trainer:
  exp_name: dualcodec_stream_with_whisper
  max_tokens: 2000
  batch_size: 13
  cfg:
    semantic_vq: true
    lambda_semantic_commitment_loss: 0.25
    lambda_semantic_codebook_loss: 1.0
    lambda_distill_loss: 15.0
    add_semantic_spec_loss: true
    train:
      max_steps: 400000
      save_checkpoint_stride:
        - 1000
      keep_last: [100]
      disable_mixed_precision: true
